name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

  deploy:
    name: Deploy on Heroku
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "f1539f12-4eec-4700-a4ca-8060f312c247"
          heroku_app_name: "vrm-go-workshop-artemchikus"
          heroku_email: "fil.ar.alex@gmail.com"
          usedocker: true
