name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

  deploy:
    name: Deploy on Heroku
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          # heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          # heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          # heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_api_key: "239297e9-3b13-4df5-9382-0885a17a7be5"
          heroku_app_name: "vrm-go-workshop-artemchikus"
          heroku_email: "fil.ar.alex@gmail.com"
          usedocker: true
